### ISSUE TITLE
Question on how to set the PID for ESP32-S3R8

### ISSUE THREAD

**Issue by James-4DSystems** [espressif/usb-pids#101]
Hello,

We are in the process of using many ESP32-S3R8 modules, and have found its possible to change the PID and reserve them via this Repo which is great. However what is lacking is information on how you actually change the PID value of the device.

I understand you do it over the USB-C connection, which is totally fine for our products, but what software do you use? 
Is there an exact procedure on how you achieve this, as we cannot find the detail. Our contact at Espressif has been sending random links which are hardly even relevant and not helpful, so we cannot find the detail we need to know on how to set the PID after our products have been built on the production line. All we want to change is the PID and potentially the description, using the Espressif VID as per this repo.

Please can you assist with some direction, as I am not getting anywhere via email with Espressif.

Thanks

**Comment by Spritetm** [comment]
That is somewhat offtopic, but generally you'd use the USB-OTG peripheral to define your own device. For Arduino, there's an example [here](https://espressif-docs.readthedocs-hosted.com/projects/arduino-esp32/en/latest/api/usb_msc.html#firmwaremsc). As far as I can see, you'd define your own PID by doing ``USB.PID(0x8123)``.

**Comment by James-4DSystems** [comment]
> That is somewhat offtopic here, but generally you'd use the USB-OTG peripheral to define your own device. For Arduino, there's an example [here](https://espressif-docs.readthedocs-hosted.com/projects/arduino-esp32/en/latest/api/usb_msc.html#firmwaremsc). As far as I can see, you'd define your own PID by doing `USB.PID(0x8123)`. Note that you can't change the PID of the USB-JTAG-serial device; that is hardcoded.

Thanks, we had already tried that though and it just doesnt seem to work.

Will keep investigating, as there must be a way to apply these PID values assigned in this repo, without compiling firmware via the IDF.

Just cannot find the information - its odd its this difficult to find.

**Comment by Spritetm** [comment]
Potentially that's a bug - suggest you post the minimum code that *should* work to the esp32-arduino github as a bug report.

**Comment by Spritetm** [comment]
Closing this as it seem to be resolved/resolving in the mentioned thread.
